
name: Gradle Package

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: '30 12 * * 3'
    - cron: '0 22 * * 5'
permissions:
  contents: read
  actions: read




jobs:
  build:
    strategy:
      max-parallel: 3
      matrix:
        version: [ 11, 13, 17 ]
        os: [ ubuntu-latest,windows-latest,macos-latest ]
      exclude: 
        - os: ubuntu-latest
          version: 17

    runs-on:  ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.version }}
        distribution: 'zulu'
        server-id: github
        settings-path: ${{ github.workspace }}


    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew build

